name: Docker Image CI

on:
  push:
    branches: [ "development", "test" ]
  pull_request:
    branches: [ "development", "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag identity-matching-server:$(date +%s) --platform x86_64
